package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// MIKO -->
/**
 * Dattebayo Orange — the original Dattebayo (2026-08-16) palette, kept as an opt-in theme.
 * It was the default theme until the Miko red repaint; nobody loses it.
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #F26B1D
 * Secondary #F26B1D
 * Tertiary #666000
 * Neutral #85736B
 */
internal object DattebayoOrangeColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB68F),
        onPrimary = Color(0xFF552100),
        primaryContainer = Color(0xFF783200),
        onPrimaryContainer = Color(0xFFFFDBCA),
        inversePrimary = Color(0xFF9C4300),
        secondary = Color(0xFFE6BEAB), // Unread badge
        onSecondary = Color(0xFF432B1F), // Unread badge text
        secondaryContainer = Color(0xFF5C4033), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(0xFFFFDBCA), // Navigation bar selector icon
        tertiary = Color(0xFFD2CA62), // Downloaded badge
        onTertiary = Color(0xFF353200), // Downloaded badge text
        tertiaryContainer = Color(0xFF4D4900),
        onTertiaryContainer = Color(0xFFEFE67B),
        background = Color(0xFF1A120D),
        onBackground = Color(0xFFF0DFD8),
        surface = Color(0xFF1A120D),
        onSurface = Color(0xFFF0DFD8),
        surfaceVariant = Color(0xFF53433C), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFD8C2B9),
        surfaceTint = Color(0xFFFFB68F),
        inverseSurface = Color(0xFFF0DFD8),
        inverseOnSurface = Color(0xFF382E2A),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFFA08D84),
        outlineVariant = Color(0xFF53433C),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF1A120D),
        surfaceBright = Color(0xFF42372F),
        surfaceContainerLowest = Color(0xFF140D08),
        surfaceContainerLow = Color(0xFF221A15),
        surfaceContainer = Color(0xFF271E19), // Navigation bar background
        surfaceContainerHigh = Color(0xFF322823),
        surfaceContainerHighest = Color(0xFF3D332D),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF9C4300),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDBCA),
        onPrimaryContainer = Color(0xFF341100),
        inversePrimary = Color(0xFFFFB68F),
        secondary = Color(0xFF765848), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFFFDBCA), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFF2C160A), // Navigation bar selector icon
        tertiary = Color(0xFF666000), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFFEFE67B),
        onTertiaryContainer = Color(0xFF1E1D00),
        background = Color(0xFFFFF8F6),
        onBackground = Color(0xFF221A15),
        surface = Color(0xFFFFF8F6),
        onSurface = Color(0xFF221A15),
        surfaceVariant = Color(0xFFF5DED4), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF53433C),
        surfaceTint = Color(0xFF9C4300),
        inverseSurface = Color(0xFF382E2A),
        inverseOnSurface = Color(0xFFFFEDE6),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF85736B),
        outlineVariant = Color(0xFFD8C2B9),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFE7D7D0),
        surfaceBright = Color(0xFFFFF8F6),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFFF1EB),
        surfaceContainer = Color(0xFFFCEBE3), // Navigation bar background
        surfaceContainerHigh = Color(0xFFF6E5DE),
        surfaceContainerHighest = Color(0xFFF0E0D8),
    )
}
// MIKO <--
