package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// MIKO -->
/**
 * Colors for Onyx Gold theme
 * Warm near-black surfaces with a gold accent.
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #FEA628
 * Secondary #F8B993
 * Tertiary #D4DD58
 * Neutral #353534
 */
internal object OnyxGoldColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFCC92),
        onPrimary = Color(0xFF472A00),
        primaryContainer = Color(0xFFFEA628),
        onPrimaryContainer = Color(0xFF6A4000),
        inversePrimary = Color(0xFF865300),
        secondary = Color(0xFFF8B993), // Unread badge
        onSecondary = Color(0xFF4C260B), // Unread badge text
        secondaryContainer = Color(0xFF673C1F), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(0xFFE4A883), // Navigation bar selector icon
        tertiary = Color(0xFFD4DD58), // Downloaded badge
        onTertiary = Color(0xFF303300), // Downloaded badge text
        tertiaryContainer = Color(0xFFB8C13E),
        onTertiaryContainer = Color(0xFF494D00),
        background = Color(0xFF131313),
        onBackground = Color(0xFFE5E2E1),
        surface = Color(0xFF131313),
        onSurface = Color(0xFFE5E2E1),
        surfaceVariant = Color(0xFF353534), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFD8C3AE),
        surfaceTint = Color(0xFFFFB963),
        inverseSurface = Color(0xFFE5E2E1),
        inverseOnSurface = Color(0xFF313030),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFFA08D7A),
        outlineVariant = Color(0xFF534434),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF131313),
        surfaceBright = Color(0xFF3A3939),
        surfaceContainerLowest = Color(0xFF0E0E0E),
        surfaceContainerLow = Color(0xFF1C1B1B),
        surfaceContainer = Color(0xFF201F1F), // Navigation bar background
        surfaceContainerHigh = Color(0xFF2A2A2A),
        surfaceContainerHighest = Color(0xFF353534),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF865300),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDDB9),
        onPrimaryContainer = Color(0xFF2B1700),
        inversePrimary = Color(0xFFFFB963),
        secondary = Color(0xFF805133), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFFFDBC8), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFF321300), // Navigation bar selector icon
        tertiary = Color(0xFF5F6300), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFFE2EB64),
        onTertiaryContainer = Color(0xFF1B1D00),
        background = Color(0xFFFFF8F4),
        onBackground = Color(0xFF1F1B17),
        surface = Color(0xFFFFF8F4),
        onSurface = Color(0xFF1F1B17),
        surfaceVariant = Color(0xFFF0E0D0), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF534434),
        surfaceTint = Color(0xFF865300),
        inverseSurface = Color(0xFF353534),
        inverseOnSurface = Color(0xFFF6EFEA),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF857462),
        outlineVariant = Color(0xFFD8C3AE),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFE0D8D3),
        surfaceBright = Color(0xFFFFF8F4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFBF2EC),
        surfaceContainer = Color(0xFFF5ECE6), // Navigation bar background
        surfaceContainerHigh = Color(0xFFEFE7E1),
        surfaceContainerHighest = Color(0xFFE9E1DB),
    )
}
// MIKO <--
