package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// MIKO -->
/**
 * Colors for Default theme (Miko)
 * Miko red, the shrine-maiden hakama red, is the brand palette since 2026-08-17.
 * The original blue palette lives on as [ClassicColorScheme]; the previous orange default
 * lives on as [DattebayoOrangeColorScheme].
 * M3 colors generated by Material Theme Builder (https://goo.gle/material-theme-builder-web)
 *
 * Key colors:
 * Primary #C62828
 * Secondary #775652
 * Tertiary #705C2E
 * Neutral #857371
 */
// MIKO <--
internal object TachiyomiColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFFFFB4AB),
        onPrimary = Color(0xFF690005),
        primaryContainer = Color(0xFF93000A),
        onPrimaryContainer = Color(0xFFFFDAD6),
        inversePrimary = Color(0xFFC62828),
        secondary = Color(0xFFE7BDB8), // Unread badge
        onSecondary = Color(0xFF442926), // Unread badge text
        secondaryContainer = Color(0xFF5D3F3B), // Navigation bar selector pill & pro
        onSecondaryContainer = Color(0xFFFFDAD6), // Navigation bar selector icon
        tertiary = Color(0xFFDFC38C), // Downloaded badge
        onTertiary = Color(0xFF3E2E04), // Downloaded badge text
        tertiaryContainer = Color(0xFF564419),
        onTertiaryContainer = Color(0xFFFCDFA6),
        background = Color(0xFF1A1110),
        onBackground = Color(0xFFF1DEDC),
        surface = Color(0xFF1A1110),
        onSurface = Color(0xFFF1DEDC),
        surfaceVariant = Color(0xFF534341), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFFD8C2BF),
        surfaceTint = Color(0xFFFFB4AB),
        inverseSurface = Color(0xFFF1DEDC),
        inverseOnSurface = Color(0xFF362F2E),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        outline = Color(0xFFA08C8A),
        outlineVariant = Color(0xFF534341),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF1A1110),
        surfaceBright = Color(0xFF423735),
        surfaceContainerLowest = Color(0xFF140C0B),
        surfaceContainerLow = Color(0xFF231918),
        surfaceContainer = Color(0xFF271D1C), // Navigation bar background
        surfaceContainerHigh = Color(0xFF322826),
        surfaceContainerHighest = Color(0xFF3D3231),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFFC62828),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFDAD6),
        onPrimaryContainer = Color(0xFF410002),
        inversePrimary = Color(0xFFFFB4AB),
        secondary = Color(0xFF775652), // Unread badge
        onSecondary = Color(0xFFFFFFFF), // Unread badge text
        secondaryContainer = Color(0xFFFFDAD6), // Navigation bar selector pill & progress indicator (remaining)
        onSecondaryContainer = Color(0xFF2C1512), // Navigation bar selector icon
        tertiary = Color(0xFF705C2E), // Downloaded badge
        onTertiary = Color(0xFFFFFFFF), // Downloaded badge text
        tertiaryContainer = Color(0xFFFCDFA6),
        onTertiaryContainer = Color(0xFF261A00),
        background = Color(0xFFFFFBFF),
        onBackground = Color(0xFF201A19),
        surface = Color(0xFFFFF8F7),
        onSurface = Color(0xFF201A19),
        surfaceVariant = Color(0xFFF5DDDA), // Navigation bar background (ThemePrefWidget)
        onSurfaceVariant = Color(0xFF534341),
        surfaceTint = Color(0xFFC62828),
        inverseSurface = Color(0xFF362F2E),
        inverseOnSurface = Color(0xFFFBEEEC),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF857371),
        outlineVariant = Color(0xFFD8C2BF),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFE4D7D5),
        surfaceBright = Color(0xFFFFF8F7),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFFEF1EF),
        surfaceContainer = Color(0xFFF8EBE9), // Navigation bar background
        surfaceContainerHigh = Color(0xFFF2E5E3),
        surfaceContainerHighest = Color(0xFFEDE0DE),
    )
}
