package tachiyomi.source.kotatsu

import org.koitharu.kotatsu.parsers.model.MangaParserSource
import java.security.MessageDigest

/**
 * Stable source ids for Kotatsu parsers.
 *
 * Same recipe as `HttpSource.generateId` (first 8 bytes of the MD5 of a key, big endian, sign bit
 * cleared) but over `"kotatsu/<MangaParserSource.name>"`, so the ids can never collide with the ones
 * generated by installed extensions from `"<name>/<lang>/<versionId>"`.
 *
 * The key deliberately uses the *enum entry name* and not the human readable title: titles change
 * upstream without warning, entry names are the parser's identity and renaming one is already a
 * breaking change on the library side.
 */
object KotatsuSourceIds {

    const val KEY_PREFIX = "kotatsu/"

    fun idOf(source: MangaParserSource): Long = idOf(source.name)

    /**
     * @param name a [MangaParserSource.name]. Kept separate so callers that only have a
     * `MangaSource` (the minimal interface the parsers library passes around) can resolve the id
     * without an unchecked cast.
     */
    fun idOf(name: String): Long {
        val bytes = MessageDigest.getInstance("MD5").digest((KEY_PREFIX + name).toByteArray())
        return (0..7).map { bytes[it].toLong() and 0xff shl 8 * (7 - it) }.reduce(Long::or) and Long.MAX_VALUE
    }

    /** Name of the [android.content.SharedPreferences] file shared with Mihon's per-source settings screen. */
    fun preferenceKeyOf(name: String): String = "source_${idOf(name)}"
}
